### ISSUE TITLE
Add node count

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/clustertpr#26]
Right now, we use an array to specify how many masters/workers we want:

```yaml
    masters:
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"

    workers:
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"
```

I think it would make more sense to do something like:

```yaml
    masters:
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"
      count: 1

    workers:
    - imageid: "ami-d60ad6b9"
      instancetype: "t2.medium"
      count: 3
```

We would still be able to, in the future, have different types of workers; the TPO would be more readable and parsing it would be a tiny bit easier.
